### ISSUE TITLE
Is there a directory equivalent to '/home/user/workspace/syntactic_parser/tensorflow_models/syntaxnet'?

### ISSUE THREAD

**Issue by huileiw** [short-edition/syntaxnet-wrapper#3]

**Comment by huileiw** [comment]
Is there a directory equivalent to '/home/user/workspace/syntactic_parser/tensorflow_models/syntaxnet' in Mac?

**Comment by MathiasDesch** [comment]
This path just needs to target the install folder of your SyntaxNet, wherever it is for Linux, Mac or Windows.
I use myself this wrapper on a mac often and the path looks like the following : 
`/Users/Mathias/workspace/tensorflow_models/syntaxnet`
