### ISSUE TITLE
Can't get it to work on OSX

### ISSUE THREAD

**Issue by serahfarron** [short-edition/syntaxnet-wrapper#4]
Hey,

I wanted to try your wrapper and installed it on my Mac. However, I can't run the example you have in your readme.

There are two issues I'm facing:
If I try to run the example while in the root folder of the cloned syntaxnet-wrapper repo, printing dependency_output simply returns nothing. It won't print anything.

If I try to run the example outside of the cloned sytaxnet-wrapper repo, I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from syntaxnet_wrapper.wrapper import SyntaxNetWrapper
  File "/Library/Python/2.7/site-packages/syntaxnet_wrapper/__init__.py", line 5, in <module>
    config_file = yaml.load(open(path.join(path.dirname(__file__), "../config.yml")))
IOError: [Errno 2] No such file or directory: '/Library/Python/2.7/site-packages/syntaxnet_wrapper/../config.yml'
```

Any idea what I'm doing wrong?

**Comment by MathiasDesch** [comment]
Hi, 
Thanks for your feedback. I resolve the second issue https://github.com/short-edition/syntaxnet-wrapper/commit/455b6b56ebe6d3cd99cda7c7f6030f713432c5ac. The problem was with installation not copying the config file. You can now also use env var to have custom folder with the config file.

**Comment by serahfarron** [comment]
Hi,

thank you for your help!
In the meantime, I also tried it on a Unix machine (running Ubuntu 16.04) and I have the same issue. The variable won't print for some reason. 
However, I found out that it still writes everything correctly to a file located here:
/tmp/stdout.tmp

I also got a new error on the OSX system (though it only appears sometimes...):
```
F syntaxnet/text_formats.cc:117] Check failed: fields.size() >= 8 (1 vs. 8)Every line has to have at least 8 tab separated fields.
Abort trap: 6
```

**Comment by MathiasDesch** [comment]
Hi @serahfarron ,

Indeed I have also this behavior, It might have appeared with recent modifications since it was not doing that previously. Im glad there is a workaround on this and that you can still enjoy our work.

I keep the issue open for people having the same problem and as a reminder that I have to work on that to make clearer/easier use.

**Comment by MathiasDesch** [comment]
Hi @serahfarron,
I think I solved the problem. As you mentioned, the stdout was reconfigured making everything acting weird for someone who does not know that the stdout is not usable anymore. 
The redirection is now only made during the parse function, you can print before, after, and print directly the result.

For more detail refer to the commit https://github.com/short-edition/syntaxnet-wrapper/commit/b51e5b591d5a3b590f76aed348bf070b68bdc494

I let you close the issue if you consider it eventually solved

**Comment by MathiasDesch** [comment]
Closing it because of lack of activity and presumed solved
