### ISSUE TITLE
cannot import graph builder

### ISSUE THREAD

**Issue by hanky-adhi-chandra** [short-edition/syntaxnet-wrapper#5]
Hi mathias.
I have problem during 

python -m unittest discover syntaxnet_wrapper

It seems that the new syntaxnet no more include graph_builder in their default installation script.

Below is detailed output

E....................
======================================================================
ERROR: test.test_wrapper (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_wrapper
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/henky/sandbox/syntaxnet-wrapper/syntaxnet_wrapper/test/test_wrapper.py", line 5, in <module>
    from syntaxnet_wrapper.wrapper import *
  File "syntaxnet_wrapper/wrapper.py", line 6, in <module>
    from syntaxnet_wrapper.parser_eval import SyntaxNetConfig, SyntaxNetProcess, configure_stdout
  File "syntaxnet_wrapper/parser_eval.py", line 52, in <module>
    from syntaxnet import graph_builder
ImportError: cannot import name graph_builder

this is my config.xml
syntaxnet:
    ROOT_DIR: /home/henky/sandbox/models/syntaxnet
    PARSER_EVAL: bazel-bin/syntaxnet/parser_eval
    CONTEXT: syntaxnet/models/parsey_universal/context.pbtxt
    MODEL: syntaxnet/models/parsey_universal

Thank you .

Best regards,
henky

**Comment by MathiasDesch** [comment]
Hi @hanky-adhi-chandra ,
I can not reproduce the issue. First of all, is the syntaxnet demo example working correctly?

**Comment by hanky-adhi-chandra** [comment]
Hi Mathias, 

Yes it is.
Here is the output

INFO:tensorflow:Read 1 documents
Input: Bob brought the pizza to Alice .
Parse:
brought VBD ROOT
 +-- Bob NNP nsubj
 +-- pizza NN dobj
 |   +-- the DT det
 +-- to IN prep
 |   +-- Alice NNP pobj
 +-- . . punct

**Comment by MathiasDesch** [comment]
All right, I will have extensive test when I  have time. Checking on the newest version of syntaxnet

**Comment by hanky-adhi-chandra** [comment]
Ok , thank you Mathias

**Comment by MathiasDesch** [comment]
Hi,

I tried to install syntaxnet wrapper using the last syntaxnet version and I did not have any problem. Moreover, the official repository is [still using this import](https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/parser_eval.py#L31), I think the graph_builder is still in SyntaxNet.

**Comment by hanky-adhi-chandra** [comment]
Hi Mathias,
I already reinstall and the problem persists.
Did you perform any extra steps other than the one they wrote on https://github.com/tensorflow/models/tree/master/syntaxnet Installation / Manual Installation step ?
I there aren't I might better ask this in SyntaxNet github repository

**Comment by MathiasDesch** [comment]
I do not perform any extra steps. I will try on a 14.04 machine, hoping to be able to reproduce this issue.

**Comment by MathiasDesch** [comment]
Can not reproduce and lack of activity
