### ISSUE TITLE
ImportError: No module named wrapper

### ISSUE THREAD

**Issue by egregorius** [short-edition/syntaxnet-wrapper#8]
Hello,

I tried using your wrapper but I got some problems. When I run unit test, I got 1 error which is 'ImportError: cannot import name tensor' (I had Theano installed on my machine) so I skipped this process and go to python directly.

In python, I can do 'import syntaxnet_wrapper' but I can't do 'from syntaxnet_wrapper.wrapper import SyntaxNetWrapper' with exception 'ImportError: No module named wrapper'.

What should I do?

**Comment by MathiasDesch** [comment]
Hi,

Indeed I added the `src`subfolder not a long time ago which might have break things for import from python. I will take a look and let you know.

**Comment by MathiasDesch** [comment]
I add pre-import of SyntaxNetWrapper in commit f62ee9. This should solve your issue since you can now do :
